### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by wessx** [oblitum/Interception#100]
Hi, I apologise but I'm very new to this. I'm trying to uninstall this programme because I don't think it's  working (trying to follow a post tutorial on Parsec and mapping keyboard) but I'm not sure how to do it or where to go? 

I saw the previous post on deleting using admin command but I don't know where to navigate in the command prompt to enter in the command you provided previously. Could I ask for some help regarding that!

**Comment by oblitum** [comment]
Sorry but no, software is not made for beginners, it's for developers, all instructions are available already.

**Comment by wessx** [comment]
I figured out how to uninstall it. I think everyone starts from somewhere, even developers. But thank you for taking the time to respond to my question, I appreciate it.
