### ISSUE TITLE
Enabling mouse/keyboard interception separately

### ISSUE THREAD

**Issue by Kaptard** [oblitum/Interception#101]
Is there some way to install the driver for mouse or keyboard input only?

I'm using an application that tends to max out all CPU cores at times, which results in key releases being registered way too late. That's happening even with no interception scripts running which could cause significant lag.

**Comment by oblitum** [comment]
Currently no, installers will install both drivers. But what you're stating shouldn't be an issue if you follow tutorial and samples that raise process priority of the application using interception, that should always be done actually (such process itself shouldn't take too long to respond input too, give its higher priority).
