### ISSUE TITLE
Access denied when installing

### ISSUE THREAD

**Issue by Hojiez** [oblitum/Interception#106]
So when i open install-interception
it opens cmd and then it closes immediately

after that i tried out another solution, this time it almost works
what i did was
open cmd as admin
and then i type in the directory for the installer
after that i type install-interception.exe in cmd and then this pops up

![image](https://user-images.githubusercontent.com/70999534/92561747-5c497680-f2a7-11ea-95a7-fc41c30e76b1.png)

it got me excited and all until i type
/install
![image](https://user-images.githubusercontent.com/70999534/92561772-68cdcf00-f2a7-11ea-8d1f-202c09ca3650.png)

Is there any way to solve this?

**Comment by oblitum** [comment]
You're not following usage.
