### ISSUE TITLE
Find Device Dynamic ID

### ISSUE THREAD

**Issue by dannyrb** [oblitum/Interception#107]
Hello! Great piece of software! Thank you for developing it and taking the time to open source it.

I'm facing an issue similar to other users. I have two devices that have the same hardware id. I've found the method that allows me to query for the hardware id, but I've been unable to find where/how to query for a device's id.

If you're able to provide some guidance, I am more than happy to author a PR to add the functionality if it doesn't exist.

---

If you're curious, my use case is for a home built arcade cabinet. Two players are "one keyboard" and the other two players are "one keyboard"

**Comment by oblitum** [comment]
Check the [identify sample](https://github.com/oblitum/Interception/blob/master/samples/identify/identify.cpp), the dynamic id is simply the id returned by wait function, it will be the same id for a given device, once there's no reboot or device reconnect. By the way, nice application, sorry the late reply.
