### ISSUE TITLE
How Can I Install The DLL?

### ISSUE THREAD

**Issue by HarlenY** [oblitum/Interception#108]
**Yo Im HarlenY And Looking For API I Rebuilt ur Project And Signed Using Certificates for dll.**

All i want to make `install driver dll` file to `mouse.sys` file?

i think u can tell me because no one is saying how can i do.

i re-complied ur driver library x86 dll for WDK7.1, And Right now ur Driver But idk how can i install ur driver for mouse.sys file.

i used `REGSVR32.exe` For Register but that is now worked  Error `( DLLENTRPOINTWASNOTFOUND )`. But ur `install-interception` is working perfectly.

_i dont want ur install-interception source code all i want how can i do install dll to mouse.sys_

have a nice days dude

<3

**Comment by HarlenY** [comment]
i Really Need ur help bro because i need to make my project work for my colleage? pls tell me how can i install the dll file in mouse.sys

**Comment by oblitum** [comment]
Seriously, I can't understand what you're asking at all. Please ask such questions by email to avoid polluting the issue tracker.
