### ISSUE TITLE
Need to reinstall driver after Windows 10 update

### ISSUE THREAD

**Issue by djlastnight** [oblitum/Interception#113]
Hi, thanks for your work. I am using your driver/api at my KeyboardSplitter application for several years. Everything is fine, except one little issue, which I am facing recently. After I update my W10, I must re-install the upper filter driver (uninstall, reboot, fresh install) in order to make it work. Note that the device and the driver files both stays at the right locations. Probably the issue is completely Windows OS related, but I was wondering what you think about it.

Thanks for your time,
Ivan

**Comment by SakhnevichKirill** [comment]
I am also interested and waiting for your answer.

Thanks for your work, 
Kirill.

**Comment by oblitum** [comment]
I've never faced this, so I don't have much idea.

**Comment by djlastnight** [comment]
Got it, closing the issue. Thanks.
