### ISSUE TITLE
A questions about licence

### ISSUE THREAD

**Issue by KOTOEB** [oblitum/Interception#114]
Hi. I am developing commercial soft (like AutoHotkey) and i want to add an interception support there. I don't use the interception source code, only compiled dll file from releases. 

1) Can I add an interception driver installer (install-interception.exe) and interception dll file (interception.dll) to my distributive, or i shall to link an user to the latest release and user shall to download them manually?

2) My program writed on Delphi 7, so I rewrited interception.h on Delphi. Shall I open the source code of this or not?

**Comment by oblitum** [comment]
For such information please send email as requested on README of project.
