### ISSUE TITLE
Mouse Disabled With Valorant Vanguard 

### ISSUE THREAD

**Issue by AboHassan-C6** [oblitum/Interception#118]
Recently if I play valorant with interception installed I Play for like 20 min or something then my mouse suddenly disable in valorant and outside I have to restart to make it work again I found this on reddit but I have to uninstall interception if I want to play 
https://www.reddit.com/r/VALORANT/comments/genkxg/support_guide_to_fix_vanguard_disabling_mouse/
 so is there any fix for this that doesn't include uninstall interception?!!?

**Comment by oblitum** [comment]
There's a comment there for your usecase, I can't help you as it's vanguard's fault when messing with the registry.
