### ISSUE TITLE
Mouse freezes when I set a filter

### ISSUE THREAD

**Issue by inGyni** [oblitum/Interception#119]
Hello, 

I am writing a program that moves my mouse automatically when I noticed that my mouse freezes when I launch it

![image](https://user-images.githubusercontent.com/47601790/116498114-42e25280-a8a9-11eb-92a2-1e69ec7075bd.png)

after debugging I noticed that the line that is underlined by red is what freezes my mouse.
I am not sure why, would you mind telling me how I can try to understand this more, and if there is a fix?

Sorry, I don't really use C++ a lot, so I might have made a silly mistake.

**Comment by oblitum** [comment]
It's expected that your mouse won't respond anymore by itself after you hook it, now it's your job to read its events and send others (or the same events) in place.
