### ISSUE TITLE
where is the source code of the driver itself ?

### ISSUE THREAD

**Issue by LastExceed** [oblitum/Interception#120]
the way i understood it is that interception is a library that interfaces with a kernel mode driver which intercepts inputs on a very low level (please correct me if im wrong), and it looks like this repository only contains the source of the library, not the driver itself. or at least i can't figure out where `install-interception.exe` in the releases is coming from. where can i find it ?

**Comment by oblitum** [comment]
Open to licensees only. Check readme.
