### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by Sebbb** [oblitum/Interception#123]
Hello,

I tried installing it, on a current Windows 20H2, from an admin command prompt:

```
C:\Users\seb\Downloads\Interception\command line installer>install-interception.exe /install

Interception command line installation tool
Copyright (C) 2008-2018 Francisco Lopes da Silva

Could not write to \system32\drivers

C:\Users\seb\Downloads\Interception\command line installer>echo "test" > \Windows\System32\drivers\test.txt

C:\Users\seb\Downloads\Interception\command line installer>type \Windows\System32\drivers\test.txt
"test"

```

Any idea?

Thanks,
Sebastian

**Comment by oblitum** [comment]
I did an installation just yesterday on a fully up-to-date system without any issues. You should check whether you have some bad AV software enabled and giving a false positive, or whether `keyboard.sys` and/or `mouse.sys` is present in the `drivers` directory, which would indicate an existing installation, in that case it's recommended to `/uninstall` then `/install`.

**Comment by Sebbb** [comment]
Hello, no AV, only Windows Defender. Fresh Windows installation without any Bloatware. Tried /uninstall and /install again, didn't work.

Is it correct that the path shows "\system32\drivers", not e.g. "C:\Windows\system32\drivers"?

No mouse.sys or keyboard.sys in %windir%\system32\drivers

Where does the installation take those files from, are they embedded in the installer exe?

**Comment by oblitum** [comment]
Yes, the drivers are embedded in the installer. Indeed, it doesn't display the exact full path in the log, `\system32\drivers` is appended to `GetSystemDirectory` output, so usually it's `C:\Windows\system32\drivers` in full (the system directory can be verified with the "System Information" tool). Recently installed and tested on:

```
Edition        Windows 10 Pro
Version        20H2
Installed on   7/‎13/‎2021
OS build       19042.1110
Experience     Windows Feature Experience Pack 120.2212.3530.0
```

**Comment by oblitum** [comment]
I'm out of ideas as tested system is similar and the installer just tries to put some file at `\system32\drivers` and fails.

**Comment by oblitum** [comment]
One tip is trying installation right after reboot. Windows sometimes have these issues of locking up file/directory access.

**Comment by Sebbb** [comment]
If you add '\system32\drivers" to GetSystemDirectory that's probably the issue?

This is already "C:\Windows\system32", so the complete path would be C:\Windows\system32\system32\drivers

Will try...

**Comment by oblitum** [comment]
Sorry, just `\drivers\file.sys` is appended. It's correct.

**Comment by Sebbb** [comment]
Rebooted (again), then it worked indeed. No idea what went wrong there before :(

Thanks, I will close this issue...

**Comment by JIGASHI** [comment]
**Is it possible to do it manually somehow? Not working for me.**
