### ISSUE TITLE
I have an old driver "catm.sys" that I cant uninstall

### ISSUE THREAD

**Issue by nsuth** [oblitum/Interception#125]
I have a driver on my mouse "catm.sys" with the provider "Oblita" and it doesnt seem to uninstall. I've installed then uninstalled interception which adds and removes keyboard & mouse.sys but not this catm.sys file. Can anyone help?

**Comment by oblitum** [comment]
You either installed a licensee's variant, or an illegal one. In any case you need to look for the origin of installation because here there's no `catm.sys`. It would be of help if you shared what's the installation source/origin.
