### ISSUE TITLE
Where is command line installer?

### ISSUE THREAD

**Issue by kassimir** [oblitum/Interception#126]
Instructions talk about using `install-interception`. That is not a recognized command anywhere in the project. I've run both the buildit commands after installing the Windows Driver Kit, and those were successful. But the readme and the website both state I need to run `install-interception`, but that doesn't work at all.

**Comment by oblitum** [comment]
Sources build library and samples, not installer, it's closed, [available from releases page](https://github.com/oblitum/Interception/releases).
