### ISSUE TITLE
Could not write to \system32\drivers

### ISSUE THREAD

**Issue by SecretsFiles** [oblitum/Interception#129]
![image](https://user-images.githubusercontent.com/71527370/142796164-ef833c81-17ce-4f45-8363-cc2f0cf4b0fb.png)

I run the cmd as administrator and I get that error. Any solution?

**Comment by oblitum** [comment]
See https://github.com/oblitum/Interception/issues/123#issuecomment-881603233.

Closing as duplicate for now.

**Comment by SecretsFiles** [comment]
It was solved, I don't know what it was

**Comment by JIGASHI** [comment]
**Idk why, but I get this error and nothing seems to work, tried restart, safe mode, even ownership change though it may have failed somehow.**
