### ISSUE TITLE
oblitum interception driver not loaded

### ISSUE THREAD

**Issue by dnepla** [oblitum/Interception#13]
After I have reinstalled intercept I have this error message.
Are you able to tell me what happen
Thank you very much for your help
D

**Comment by oblitum** [comment]
Was it working and you tried to install a second time and it stop working?

**Comment by oblitum** [comment]
In the same machine? Did you tried to uninstall it? Did you reboot after installation?

**Comment by dnepla** [comment]
yes
was working perfectly and in the same machine.
i did reboot

very strange
![nuovo immagine bitmap](https://cloud.githubusercontent.com/assets/11651047/6830500/54b5921c-d31a-11e4-84c5-aa351c54ac26.jpg)

**Comment by oblitum** [comment]
Can you tell me whether it stopped after you tried to reinstall or did you tried to reinstall because it stopped working all of a sudden.

**Comment by dnepla** [comment]
no just a format of my hard drive. it was full with and with many errors. Before that your program worked perfectly

**Comment by dnepla** [comment]
moreover, I saw that if I type the command in uppercase, returns the string without errors.
Of course the string without starting the program

**Comment by dnepla** [comment]
![nuovo immagine bitmap](https://cloud.githubusercontent.com/assets/11651047/6831002/de714390-d31d-11e4-9114-922d9bd174f0.jpg)

**Comment by oblitum** [comment]
This output is not part of Interception. I have no idea where it comes from. Are you a user of this program that uses the Interception library & drivers or the developer of it? 

Would please provide information from where you downloaded it?

**Comment by dnepla** [comment]
I'd like to remapping the entire keyboard. I use it for flight simulator. I do not use your library. but for now I just tried to open the program and this is the result. No key has been inserted yet because of the error

**Comment by oblitum** [comment]
It may be a problem with the program you're using, not the library, or your system. I'm afraid I can't help if you're not the developer of the program.

Still I would like you pointed me to where you download such program.

**Comment by dnepla** [comment]
I have downloaded few month ago, I really don't remember. Some website for flight simulator entusiasts but I don't remember wich one. I'm sure the file is the same because I always save on a separate disk my files exe

**Comment by oblitum** [comment]
It may be the same, but I can't tell whether this program has a bug using the library because I didn't build it.

**Comment by dnepla** [comment]
ok thanks
