### ISSUE TITLE
When i use interception, my mouse freezes and even if i unplug it, it doesnt work. Any solution?

### ISSUE THREAD

**Issue by Courage1ei** [oblitum/Interception#130]

**Comment by oblitum** [comment]
Check whether you have too many devices connected, or a few devices that act like multiple ones each, or you reconnect devices too often, you may hit #25 due to that, there's no public fix for that.

If "freeze" means it's lagging instead of stopping, then see #90 for resolution.

**Comment by Courage1ei** [comment]
> 

I only have a mouse and a headset connected, and i used interception when i rebooted my pc, so there should be no extra app running. But it still freezes

**Comment by oblitum** [comment]
You need to provide more information about **how** you're using it and **when** it "freezes". Besides the information I have already given, I'm unable to go any further without more detail.

**Comment by Courage1ei** [comment]
> You need to provide more information about **how** you're using it and **when** it "freezes". Besides the information I have already given, I'm unable to go any further without more detail.

I use interception for a valorant cheat, everytime when i run the cheat, it also activated interception, then my mouse is frozen right after interception was activated , but the pc is still running, only my mouse driver crashes.

**Comment by oblitum** [comment]
Then that means interception is working, because it's a driver that starts on boot, so it's already running before that happens. When you do that, either the program that calls interception is buggy, or some other program that tries to block it, but it's most certainly not a interception issue. It's out of scope of this project support too.

**Comment by Courage1ei** [comment]
> Then that means interception is working, because it's a driver that starts on boot, so it's already running before that happens. When you do that, either the program that calls interception is buggy, or some other program that tries to block it, but it's most certainly not a interception issue. It's out of scope of this project support too.

Thanks for ur reply🤞
