### ISSUE TITLE
remote usage

### ISSUE THREAD

**Issue by Dessp1** [oblitum/Interception#132]
Hello, 
This library is fantastic.
Work fine on local computer. 

When I try to run it remotely, it not recognize keyboard on mouse (with TeamViewer for ex.) 

Is there a way to "hack" the system to be able to run the script remotely ?

Tried by myself - can't skip the part when it waits for keyboard or mice input :) 

Regards.

**Comment by oblitum** [comment]
Closing as it's just a question.

It's probably not possible at all as it's currently just made to _intercept_ real devices, and remote interaction doesn't involve real remote clicks :), it's something virtual outside the project's current scope.
