### ISSUE TITLE
Can this intercept between MEDIA control keys?

### ISSUE THREAD

**Issue by IamSanjid** [oblitum/Interception#136]
I would like to intercept between `VK_MEDIA_PLAY_PAUSE`.
I think since the signal is getting from a different device other than Keyboard or Mouse, I think it cannot?
Or is it possible to do something like that, thank you!

**Comment by oblitum** [comment]
If it's a device different from keyboard or mouse, then it won't go through _Interception_, and it can't do nothing about that at the moment.
