### ISSUE TITLE
interception.exe cant install/uninstall someone help me

### ISSUE THREAD

**Issue by whatuhb** [oblitum/Interception#138]
I tried to install this interception because for some reason my mouse just doesn't work when I play a specific game and I searched for solutions and I found out I had to download this. But when I inserted the command as administrator, it says that the app can't be downloaded, I can neither install or delete it.
![Capture](https://user-images.githubusercontent.com/102885664/161407162-ea94deb6-b638-4856-baa1-d928d9aaea0c.PNG)

**Comment by oblitum** [comment]
Not sure whether you managed to circumvent this or gave up. To be honest I have no idea what's going as I've never saw that window before, maybe changing the exe's compatibility to an older Windows can make it go away.

**Comment by whatuhb** [comment]
I want to give up but I wanna try one last time, how do you change the exe's compatibility to an older window?
