### ISSUE TITLE
error LNK2001: unresolved external symbol __imp__interception_create_context

### ISSUE THREAD

**Issue by shiraleibo** [oblitum/Interception#14]
Hi,

I am struggling for couple of days now with using the interception library in my code.
I have a C windows driver project in visual studio 2013, and I've added the path for the include folder (interception.h) and for the interception.lib files in the linker, and still I get this error.
I also tried to change the build properties as you suggested before- to release/debug- but I still get the error.
Am I doing something wrong?
Is it possible to use the interception with VS 2013?
I am developing on Win 8.1- is this a problem?

Thanks
Shira

**Comment by oblitum** [comment]
You're probably doing some mistake linking to the DLL, never found this issue. Also notice that to install the drivers on Windows 8 you need to set compatibility mode of the installer to Windows 7 in the properties of the executable

**Comment by shiraleibo** [comment]
I am not linking the dll.
I'm setting your source to create the .lib file, and this it's path i'm adding to the Additional Library Directories box.
Should I create the dll?

thanks

**Comment by oblitum** [comment]
For static linking you must define `INTERCEPTION_STATIC` from command line parameters.

**Comment by shiraleibo** [comment]
OK,
so I have built the source as a dynamic library now, and got the dll.
I am adding it's path to my project->properties->Linker->General-> Additional Libraries Directories, and I still get the same error.
When I try to add interception.dll specifically in Linker->input->Additional Dependencies, I get the following error during compilation:
error LNK1107: invalid or corrupt file: cannot read at 0x2F0

Am I linking it wrong?

Thanks very much i really appreciate your response!

**Comment by oblitum** [comment]
You should add `.lib` files as dependencies, not `.dll` files. Also, there's the `.lib` file that's associated with the `.dll` and is generated when you compile a DLL, and there's the static and larger `.lib` file which is a static library. I'm closing this as I'm 90% sure you're having problems with your environment instead of it being a problem with the project. You can still comment though.
