### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by sinkingsugar** [oblitum/Interception#15]
I just updated to windows 10 and sadly Interception was not working.
I tried installing again (admin prompt etc) but gave a "could not write to system32\drivers" error.
Nice piece of software! I hope you can get windows 10 support up soon!

Edit: It is actually WORKING!, just the uninstall/install process is acting weird. ( I had it installed under windows 8.1 )

**Comment by oblitum** [comment]
Thanks for reporting, I'll take a lookt when I find some time and a Windows 10 machine. I'm wondering whether they have finally fixed the weird name of the system directory, `system32` at the 64 bits age.

**Comment by sinkingsugar** [comment]
Haha! well.. I had a look and looks just like before ! 64bit system.. yet system32 is filled with stuff :)

**Comment by sinkingsugar** [comment]
Just an update.. I manage to install it after a reboot! the issue might be quite small then! I'm not sure why it was complaining at that point.
I think that fresh installs might just work.

**Comment by oblitum** [comment]
Oh, cool, good to know, I'll close it for now then, if someone finds an issue I reopen it.

**Comment by UndeadBlow** [comment]
I am sorry, but I have the same problem and can't solve it for days.
Here is installer output on Windows 10: http://pastexen.com/i/TRnH1RME6M.png
Cmd was run from administrator.
Isn't better to give some more options in installer? Most of users is developers and this is good idea to give more control. Seems, that something goes wrong with paths, but I can't experiment because have only install and uninstall :)

**Comment by oblitum** [comment]
@UndeadBlow Is this an outdated installer? I think copyright years for the installer available for download are newer than 2012.

**Comment by oblitum** [comment]
@UndeadBlow Just checked, you're indeed using an old installer.

**Comment by UndeadBlow** [comment]
@oblitum I thought about that in first order, so I've download latest (summer 2015) release from here and it outputs the same :(
Here is proof:
http://pastexen.com/i/VuJBdKdLRi.png
Check the files last modified property. Maybe that is something wrong with my Windows? It it insider preview and that system a little buggy...

**Comment by oblitum** [comment]
@UndeadBlow No idea. Are you sure you're inside an administrator prompt? This is the kind of error that should happen when not running as administrator. I have no issues on Windows 10, but in case I'd run it as non admin, I would get that error for writing permissions.

**Comment by oblitum** [comment]
@UndeadBlow just run a raw cmd, not a visual studion prompt etc.

**Comment by UndeadBlow** [comment]
@oblitum The same :(
Tried from admin cmd and from C:
http://pastexen.com/i/mgCcq1pOCq.png

**Comment by oblitum** [comment]
@UndeadBlow try to run "/uninstall". I think your issue should be something with Windows locking the file, so it can't be overwritten. So, even if "/uninstall" gives an error, reboot, and just after reboot, open an admin command prompt (raw cmd), and try install again.

**Comment by oblitum** [comment]
If still **just after reboot** it doesn't work, I would try to boot in safe mode, and try install again from there. If it still doesn't work, then, I have no idea without debugging further, still, this error message only shows up when failing on file writting.

**Comment by oblitum** [comment]
@UndeadBlow if all of this doesn't work, I advice that you open an issue and detail your platform (Windows version, machine architecture, etc)

**Comment by oblitum** [comment]
@UndeadBlow also stating when it start to be a problem. Last time I installed on Windows x64 there were no problems, but maybe, after some Windows update, things changed.

**Comment by oblitum** [comment]
@UndeadBlow Also, just noticed you mention "InsiderPreview", is this newer than Windows 10, or is it an older build. I guess it may be the issue.

**Comment by UndeadBlow** [comment]
@oblitum 
Ya, just after reboot helps :)
Have no idea what kind of thing blocks the file, but thanks.

**Comment by oblitum** [comment]
@UndeadBlow at last :-)

**Comment by UndeadBlow** [comment]
@oblitum 
Okeeey, after installer wrote that installation is successful and rebooted, interception doesn't works (on win7 I used your lib many times without any problems) and when I'm tried to install or uninstall message above appears again. I've tested that on my friend machine, on official Win 10 without Insider preview and got the same message.
Do you tested interception on Win 10 x64? Seems strange one problem on two different machines.

**Comment by UndeadBlow** [comment]
On another friend's machine installation successfull with first try. Don't know what is going on -_-

**Comment by oblitum** [comment]
@UndeadBlow Indeed, it's a strange issue, I'd like to know what's going although I have no idea. It could be possibly, some antivirus software acting strangely, game protecting software that do kernel mode protection, or another software that also make use of keyboard/mouse filters and is not acting as a good citizen.

**Comment by oblitum** [comment]
I guess there should be no issue on vanilla Windows, and this problem is arising from some extra conflicting software.

**Comment by oblitum** [comment]
By the way, I don't recommend anyone to use the general AV software that's used in the wide by Windows users. Generally they just offer a false sense of protection and are a resource hog, besides frequently turning the machine less protected: https://code.google.com/p/google-security-research/issues/detail?id=693

**Comment by UndeadBlow** [comment]
@oblitum I use no AV because I'm mainly Linux user :) Also all Windows integrated security services disabled as much as possbile, so I am a little in deadlock. I'm agree with you that I'm trying to solve problem and disabled most of soft that runs with sysems but no results for now.

**Comment by oblitum** [comment]
@UndeadBlow If you're interested, I can produce a installer with more logs so that we can pin-point this more specifically. I can do this at the weekend only though.

**Comment by UndeadBlow** [comment]
@oblitum Yes, I can do everything you will require.

**Comment by oblitum** [comment]
@UndeadBlow ok, see ya at the weekend then, I'll try to build a logfull installer to check this in your machine (since I can't repro).

**Comment by oblitum** [comment]
https://github.com/oblitum/Interception/issues/15#issuecomment-126865973

**Comment by paradoxalan** [comment]
try to run "/uninstall". I think your issue should be something with Windows locking the file, so it can't be overwritten. So, even if "/uninstall" gives an error, reboot, and just after reboot, open an admin command prompt (raw cmd), and try install again.

Above instructions solved it for me
