### ISSUE TITLE
could not write to /system32/drivers

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [oblitum/Interception#159]
I need interception for ucr, but when i run interception, in cmd admin, i get, "could not write to system32/drivers." please help

**Comment by clagms** [comment]
Having the same problem. Even running cmd as administrator.

**Comment by clagms** [comment]
After a more careful investigation, this might be caused by system32 folder being read only. However, if you are not full administrator on your machine, it might be difficult to remove this constraint.

**Comment by SuperMarioYAHOOYAHOO** [comment]
mine is not read only, i created a folder in system 32.

**Comment by SuperMarioYAHOOYAHOO** [comment]
i had to restart my computer multiple times. But in the end i did get the driver up and running.
