### ISSUE TITLE
C# wrapper

### ISSUE THREAD

**Issue by oomek** [oblitum/Interception#18]
Hi, I'm having troubles in compiling your examples in Visual Studio 2015.
When I try to compile I get an error:
invalid or corrupt file: cannot read at 0x298

Would you be able by any chance to write a C# wrapper library for your dll? 
Is that even possible?

I also have problems with uninstalling your hook driver. 
I get the message:
"Error deleting \system32\drivers\keyboard.sys"
When I manualy deleted keyboard.sys and mouse.sys there was another:
"Error deleting keyboard driver key"

**Comment by oblitum** [comment]
There're C# wrappers on the web already made by other people, you may take a look at them, I won't be writing one any time soon.

Regards your issues, I've no idea, I have good reports of the library working without issues on Windows 10, and I'm using it myself for personal purposes.

**Comment by theblixguy** [comment]
Can you link me to the C# wrappers? I found one called Interceptor but it doesn't support Windows 8 or above even when your driver does
