### ISSUE TITLE
Mouse Events don't work at the game.

### ISSUE THREAD

**Issue by tolgayildiz37** [oblitum/Interception#191]
Hello,

I was using that library perfectly last year but I can't anymore. I spent many hours to fix that as you know have not anything on it. The events are still working perfect except on the game. Do you have any suggestion to fix that? Or Can I rebuild that project and try to change the name or identical stuff about the library just for using.

Sorry about my questions, I've no experience about drivers, I was just user.

**Comment by maxmanusv1** [comment]
Did you find any solution?

**Comment by unrealshape** [comment]
1. is the interception DLL the same folder with the executable file?
2. Are u have on focus on the game?
3. Give me more information or add me on discord

**Comment by maxmanusv1** [comment]
> 1. is the interception DLL the same folder with the executable file?
> 2. Are u have on focus on the game?
> 3. Give me more information or add me on discord

Yeah it is focused to the game, DLL file is in the same folder with executable file. It works on other games like Minecraft but it doesnt work for Metin2

**Comment by unrealshape** [comment]
Admin rights ?

**Comment by tolgayildiz37** [comment]
> Did you find any solution?

Yeah, I did. Device Id was wrong. I fixed it.
