### ISSUE TITLE
install-interception on Windows 8.1: "This version of Windows is not supported"

### ISSUE THREAD

**Issue by geoffff** [oblitum/Interception#20]
I tried running install-inception on my Windows 8.1 system, and I get  "This version of Windows is not supported".  You state that it should work on any version of Windows through 10.

I'm happy to dive into the source code and see what's up, but I don't see the source for install-inception. Would you be up for posting the source for this on github?

install-inception works great on my Windows 7 box.

Thanks!

**Comment by oblitum** [comment]
Well, this has never been a problem since it has been tested on Windows 8.1 and 10. I've done it myself and use it on a Windows 10 box.

Old versions of the installer didn't work, that's true, please make sure you're using the latest from the releases page.

Sources are currently not available without commercial licensing, please check README.

**Comment by oblitum** [comment]
Also, this is quite strange since this message should show up solely in case the `GetVersionEx` Windows API returned `false`. Never seen this happening with current codebase, but who knows...

**Comment by geoffff** [comment]
The version of install-interception I'm running is signed by you on Feb 15, 2012.

I found a workaround! On a whim, I right-clicked on install-interception.exe, went to Properties/Compatibility and then selected "Run this program in compatibility mode for:" [WINDOWS 7]. 

install-interception works fine in Windows 7 compatibility mode!

If I understand this documentation, GetVersionEx has been changed to now return the version of Windows specified by the compatibility options, so it makes sense that my changing this in the properties would affect its behavior. 

https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451%28v=vs.85%29.aspx

I see more on this new Windows 8.1 behavior here:

http://www.codeproject.com/Articles/678606/Part-Overcoming-Windows-s-deprecation-of-GetVe

Thanks for getting back to me. I'm good to go now, but other users of Windows 8.1 & beyond might face this issue as well.

**Comment by oblitum** [comment]
This is an old workaround that have been in use for old installers. From signed date you're running the old version. Current installer is not signed.

**Comment by geoffff** [comment]
Thank you!

Yes, it turns out I was running the old installer at https://github.com/downloads/oblitum/Interception/install-interception.exe 

I used your forum post on http://orbiter-forum.com/showthread.php?t=30829 as a reference on how to install interception, and that post points to the old install URL above. Perhaps deleting the interception-install.exe file from the old github link would prevent others making my same mistake.

**Comment by oblitum** [comment]
@geoffff fyi, it's not my post.
