### ISSUE TITLE
Where can the driver or device be seen?

### ISSUE THREAD

**Issue by j-waechter** [oblitum/Interception#23]
Can the driver or a simulated device be found anywhere in the Windows device manager or elsewhere? How can you detect that it's installed? If it's there somewhere a note about this in the docs or a read-me file would be helpful.

**Comment by oblitum** [comment]
I think it's not the role of the library to document the Windows driver model but solely its usage. Figuring out what the library creates or not is internal behavior, which is not necessary to be exposed. If I were ever to change that, I'd also need to change docs, for no useful purpose. You may check the device driver stack using proper tools like OSR DeviceTree and loaded drivers using `driverquery`.
