### ISSUE TITLE
Can it be used to send keys to specific application?

### ISSUE THREAD

**Issue by LifeH2O** [oblitum/Interception#24]
Can it be used to simulate/send inputs (both mouse and keyboard) on multiple games running on same system individually in a way that each receives input specified for it?

Currently I am hooking DirectInput but it does not work in all games. Also even in one game it does not work everywhere e.g. not on the widgets. So I am sending window messages + directinput to make it work.

**Comment by oblitum** [comment]
I've seen support for multiple mice in Windows before, I don't know the details or how it would interact with this library sorry.

When I've tested attaching multiple mice in my machine, I've just got the function of a single pointer for multiple mice, but the library will detect events individually from corresponding devices, even though what you give back to Windows will be represented by a single pointer.

I didn't try any setup of input device per window, so I can't say whether it's possible or not.
