### ISSUE TITLE
wrong InterceptionMouseStroke struct?

### ISSUE THREAD

**Issue by zeg** [oblitum/Interception#27]
data I got from stroke is 

2byte button up and down
2byte 0
2byte rolling data
2byte 0
4byte x
4byte y

windows10 x64

**Comment by oblitum** [comment]
C doesn't guarantee contiguous data members, structure padding is common, see:

- http://www.drdobbs.com/cpp/padding-and-rearranging-structure-member/240007649

It's expected from the programmer that the data structures provided should be used for member access instead of hardcoded offset access.

**Comment by zeg** [comment]
oh ~~ understand

I use autohotkey , it can only get number from raw
