### ISSUE TITLE
is there anyway to get mouse button stat more than 8?

### ISSUE THREAD

**Issue by zeg** [oblitum/Interception#28]
my mouse have 11 button, the extra 3 seems not captured

**Comment by oblitum** [comment]
Windows will probably not handle those extra buttons through the common route, what's support is listed in the header, a maximum of 5 currently.

**Comment by oblitum** [comment]
You should try to check changes in the `.state` member at last. There're macros for 5 buttons but `.state` may go beyond these macros possibly.
