### ISSUE TITLE
On intercept open WPF window

### ISSUE THREAD

**Issue by sandek** [oblitum/Interception#33]
Hello,

I have a small problem with interception, I don't know why, but if I run it with visual studio with debugger it works great, but if I run an exe interceptor, it is not working as it should.

So, on while I intercept, I am looking if a window is opened, and if it isn't, I start a program, make him active, and then write intercepted string.

The problem is, that  WPF window is not fully loaded, because  it acts differently if I start it with interceptor . exe

I hope you can help me, I am dealing with this thing for a week now, but it seems I can't find a solution.

I have even made i video, so that you can understand my problem.

https://www.youtube.com/watch?v=weM4a8H6h6w&feature=youtu.be//

Bellow is my code. 

Regards!

```
while (interception_receive(context, device = interception_wait(context), &stroke, 1) > 0)
	{
		if (interception_is_keyboard(device))
		{
			InterceptionKeyStroke &keystroke = *(InterceptionKeyStroke *)&stroke;

			if (device == 1)
			{		Sleep(20);	
				if (FindWindow(NULL, _T("MainWindow") ) == NULL) {
					Sleep(20);	
					::SetForegroundWindow(FindWindow(NULL, _T("MainWindow") ));
					Sleep(5000);
                                          // Here I am opening a shortcut named program in project folder, wich leads to my wpf program
					ShellExecuteA(NULL, "open", "C:\\project\\program", NULL, NULL, SW_SHOW);			
					Sleep(2000);
				}												
			}
		}
		size_t length = interception_get_hardware_id(context, device, hardware_id, sizeof(hardware_id));

	interception_send(context, device, &stroke, 1);
			
	}
	
    interception_destroy_context(context);	
    return 0;

```

**Comment by oblitum** [comment]
I'm sorry but I have no idea. I'm closing this as it's not being specific as an issue of the library or of your application.

**Comment by oblitum** [comment]
The only thing that comes to my mind is that you have the interception.dll in the executable path of the debugging version, but you didn't put it besides the release binary, so the DLL may be missing on release. You may check that.

**Comment by sandek** [comment]
May I ask you, if it's possible to store intercepted string in txt file? Thank you

**Comment by oblitum** [comment]
Yes. You are free to do anything with the intercepted data.

**Comment by sandek** [comment]
Can you please help me, I am pretty new to c++, is it possible that I am getting for a string 0005819175

keystroke codes: \v\v\v\v\v\v\x6\x6\t\t\x2\x2\n\n\x2\x2\b\b\x6\x6\x1c.

Do you maybe know which standard use keystroke codes?

Thank you.
````
	while (interception_receive(context, device = interception_wait(context), &stroke, 1) > 0)
	{
		if (interception_is_keyboard(device))
		{
			InterceptionKeyStroke &keystroke = *(InterceptionKeyStroke *)&stroke;

			if (device == 1)
			{		
					s+=keystroke.code;																			
			}
		}
		size_t length = interception_get_hardware_id(context, device, hardware_id, sizeof(hardware_id));
	
	interception_send(context, device, &stroke, 1);
	string k = s;
	}
	
	
    interception_destroy_context(context);	
    return 0;
}
```

**Comment by oblitum** [comment]
Sorry, I can't help everyone in basic programming matters. You need to study.
