### ISSUE TITLE
Can rename interception device

### ISSUE THREAD

**Issue by meawpipat** [oblitum/Interception#36]
Hi,
Can we rename the interception device? The issue is a anti-cheat engine (Gepard) can detect the interception.

Thanks.

**Comment by oblitum** [comment]
Hi, thanks about that information. I'm sorry but that requires driver resigning and other cumbersome compatibility related tasks, which are scheduled to be done solely at a major version upgrade from my side. The other option is to license the full sources and change it as you wish.
