### ISSUE TITLE
Update WDK with Integration with Visual Studio 2015?

### ISSUE THREAD

**Issue by htrej** [oblitum/Interception#39]
I can't seem to figure out how to "convert" the command line "buildit" scripts to work with the newer WDK (integrated with Visual Studio 2015). Is there any way you could give "solutions" (in both meanings of the word I guess, solution and *.sln) for the library/samples? I think Microsoft might've deprecated the older build command.

**Comment by oblitum** [comment]
I have some plans on upgrading, but I would simply avoid anything Visual Studio related. I don't like it and the solution files are simply a hassle do deal with, the simple build mechanism as it's now is much better, in fact, I've moved out from VS solution files which I used to use formerly.

If there's any upgrade route, it will be through [Enterprise WDK](https://msdn.microsoft.com/en-us/windows/hardware/drivers/develop/installing-the-enterprise-wdk), which would maintain a simple build procedure through the command line.

**Comment by htrej** [comment]
I looked at Enterprise WDK as well and it seems similar to WDK 7.1--how much would have to be changed for EWDK to work with the sources projects right now?

**Comment by oblitum** [comment]
It should take much to move to EWDK but I'm not look into this now as WDK 7.1 still works fine. I'm still able to download, install and use WDK 7.1 on a Windows 10 machine.

caps2esc exist for a reason: vi. I've long moved out from Visual Studio for good. I just use Vim, with some goodies when possible:

- http://nosubstance.me/articles/2015-01-29-better-completion-for-cpp/
- https://www.youtube.com/watch?v=EOsSQrwBNEw
