### ISSUE TITLE
Understanding install-interception.exe, the interception library, and the interception header

### ISSUE THREAD

**Issue by htrej** [oblitum/Interception#40]
If it isn't too much of a hassle, I was wondering if I could glean some "intuition" on the 3 players above (in the title of the issue). I'm admittedly new to this whole driver building thing, and since microsoft hasn't exactly stuck with WDK 7.1 (I'm on Windows 10, btw), it hasn't been exactly any easier for me to get a hold of what's going on (though I _have_ managed to build the necessary pieces using WDK 7--haven't figured out how to use WDK 10). All in all though, I just want to learn a thing or two.

So, to be more clear and ask more specific questions, I would like to know first what install-interception does--I don't need the source code of it or anything, I just want to know why it needs to be installed first, and whether or not it needs to be installed for every PC that runs, say, the caps2esc.exe I just built.

In addition, since I don't get what the installer does, I would not know--as a matter of course--why the Interception API library (interception.dll) still needs to be kept around at the end of everything. (So It may or may not be necessary to clarify what interception.dll does after explaining the installer above.) Nonetheless, I still do want to ask if there is any (easy) way to embed the necessary dependencies (like interception.dll) in the exe (e.g. caps2esc) so that the files are kept together.

I don't think you really need to explain what the header (or library, I guess) does, I've just tagged it along in case things get more "involved". Knowledge of what a library/header does is really not particular/unique to this project, so there is really no reason for you to explain it unless it becomes relevant to understanding Interception from a broader perspective.

I think most of the issues stem from the fact that there isn't much documentation (at all, other than your website) on this seemingly very powerful driver. If only there was sufficient documentation...

---
#### (I really do wish there were a "README" for this kind of stuff):
- What does install-interception.exe do?
- Does install-interception.exe need to be run on all computers (that run the programs)?
- What are the static and dynamic libraries (interception.dll and interception.lib) to be used for?
  - Should the libraries be kept with the exe compiled (this is just for confirmation--in all likelihood, the answer is yes)
- More importantly, how can I _embed_ the libraries into the exe (if it's possible at all)?
- Does one have to restart the exe (caps2esc for example) after every reboot? 
- Does there exist any more documentation for the API (anywhere?)

**Comment by oblitum** [comment]
- Install necessary drivers (just the needed registry settings and file placement).
- Yes. The library provided here exist to communicate with the drivers solely, without their existence, the library has no use.
- The libraries (and only them, not the drivers) are under LGPL. For them to have any use you need the currently closed source drivers, installers, etc. Licensing covering all is detailed in README and the licenses. In fact, most of these questions are already answered.
- Answered.
- No. Reboot is needed solely after install-interception.
- There's no formal API docs, but website and samples cover most usage.
