### ISSUE TITLE
Two keyboards from same manufacturer have same HID/VID Help please

### ISSUE THREAD

**Issue by wolfofwst** [oblitum/Interception#46]
Hello, I bought two of these numpads (https://www.amazon.com/dp/B01E8U8HKW/ref=cm_sw_r_sms_awdb_aTZ6ybF4DBGZZ ) to use them both at the same time with their own separate hotkeys binded to them. Problem is that interception assigns them both the same HID/VID so intercept thinks they are both the same device so only half of the hotkeys work. How can I fix this and give one of the keyboards a different id? Thanks for your time!

**Comment by oblitum** [comment]
You have to rely on the dynamic id, from project's web page:

> The following sample allows one to query for a device’s “hardware id”, which may help on disambiguation of device input.
> Just remember this hardware id’s are not required to be unique, but mostly will when you have at last two different device models.

In that case you have to use the device id's, not hardware id's, but these device id's may change on plug/unplug, reboot, etc.
