### ISSUE TITLE
Request: Installer

### ISSUE THREAD

**Issue by evilC** [oblitum/Interception#52]
Is there any chance of packaging Interception as an installed app?  
I write apps aimed at non-technical end-users (Some of whom are disabled), and it would be nice if there were a Gui app that did the install and prompted for reboot.  
I could potentially help out in this regard (I don't have experience with installers, but I work for a software company so plenty of access to people who do), but it would only really be any point if you were willing to adopt whatever we came up with into your release process.

**Comment by oblitum** [comment]
For non-commercial applications the software is provided as-is. As explained in the README, the licenses for commercial applications available additionally provide an installer DLL, so that Interception installation can be embedded in whatever 3rd part installation solution.
