### ISSUE TITLE
Are newer versions of the library compatible with older drivers?

### ISSUE THREAD

**Issue by tgharib** [oblitum/Interception#53]
I am using a [mouse acceleration driver](http://mouseaccel.blogspot.ca/p/blog-table-of-contents.html) on my machine which relies on your interception library. I'm not sure which version of the library it is using but let us say it is using v1.0.0.

I'm also developing a program that relies on your interception library. Will I be forced to use v1.0.0 of the API or can I use v1.0.1?

**Comment by oblitum** [comment]
Drivers didn't change between version, there were just minor API level bugfixes, so no problems.
