### ISSUE TITLE
Filter individual devices?

### ISSUE THREAD

**Issue by evilC** [oblitum/Interception#55]
Is it technically feasible to allow filters to be per-device?  
Ideally, I would like to reduce the amount of processing that my code needs to do, and also it would be nice if I could debug code filtering one keyboard and mouse, but still operate the debugger with another keyboard and mouse.

**Comment by oblitum** [comment]
Yes, that's what `InterceptionPredicate` if for (which you can couple both with checking device id or hardware  id), please check the main web page on its documentation.
