### ISSUE TITLE
Mouse Click

### ISSUE THREAD

**Issue by vinmred** [oblitum/Interception#60]
I need a way to handle mouse clicks such that it can send clicks based on a single variable:

PseudoCode: 
if (needClick == true) 
{
	mstroke.state = ???
}
else if (needClick == false)
{
	mstroke.state = ???
		
}
interception_send(context, device, &stroke, 1);

How do I implement this using interception.h to track mouse states to prevent unnatural behavior.

**Comment by oblitum** [comment]
Please provide a [test case](https://blog.testlodge.com/what-is-a-test-case-in-software-testing/) if you're facing an issue, pseudocode is not helpful.

The mathpointer sample deal with many mouse events, it produces both clicks and movements.

**Comment by vinmred** [comment]
The mathpointer example helped me. Thanks

**Comment by oblitum** [comment]
...
