### ISSUE TITLE
Mouse problems

### ISSUE THREAD

**Issue by greg67** [oblitum/Interception#61]
Hello. Nice program, simple to use, but unfortunately I have problems using it with AutoHotKey. 
After a while, having the script running, my mouse is getting disconneted. To get it work again I need to restart my computer. Sometimes the encountered issue is after 10 min, other times after an hour or so. 
Please help.

**Comment by oblitum** [comment]
There's no useful information in this report, I've never faced/heard of this issue, and you're relying on 3rd part software which is unrelated to this library.

If you want any help please isolate your issue in a test case using the library alone, without AutoHotKey as I don't use it.
