### ISSUE TITLE
error installing the install-interception.exe

### ISSUE THREAD

**Issue by devakumetsu** [oblitum/Interception#65]
got this error, https://imgur.com/a/pl5WR when try to install the lib.

and this error on visual studio: https://imgur.com/a/LZQQn its like the lib is not installed on the system.

Window 10 64bit.

Regards.-

**Comment by oblitum** [comment]
Hi, I can't help with second screenshot, that regards some other language binding that relies on Interception but that I know nothing about. You may ask help about it with the author.

Regarding the first screenshot, I dunno what happened that it failed install for you. Please make sure to [download the installer from here](https://github.com/oblitum/Interception/releases/latest) and try to execute it as soon as you boot your machine. If it still fails I don't know how to help further.

**Comment by evilC** [comment]
Try right-clicking Interception.dll, check if it is blocked.  
![Image](https://i.imgur.com/0RKFu4Z.png)  
See where the cursor is, if the "Unblock" checkbox exists, you must tick it.
