### ISSUE TITLE
Interested in purchasing a license 

### ISSUE THREAD

**Issue by nefarius** [oblitum/Interception#66]
Greetings!

Apologies up front if you've documented this already but I haven't found the necessary information on your page.

As the title states I'd be interested in a license but have a few questions which would require clarification first. 

I'm not a lawyer so please bear with me; with the license would I be entitled to the IP so I could modify and share the binaries and sources as well?

Is the driver utilising WDF or pure WDM?

Thanks for your time.

**Comment by oblitum** [comment]
Hi. I don't know which license you're referring to, there are two, and as I state in README, if there's interest please mail me.

**Comment by nefarius** [comment]
Whoops, overlooked that. I'll write a mail, thanks!
