### ISSUE TITLE
Windows 10 April update may break Interception

### ISSUE THREAD

**Issue by cpiscos** [oblitum/Interception#70]
Running install-interception.exe in the command line does not give /install /uninstall options. Running install-interception.exe /install in command line, rebooting, and running caps2esc does nothing.

**Comment by Alpvax** [comment]
Hasn't been an issue for me, I've had no issues installing. Did you run as administrator?

**Comment by oblitum** [comment]
No issues here too.

**Comment by cpiscos** [comment]
I misunderstood and thought the UAC warning that appeared when executing would run the program with administrative rights from the terminal. My fault, it works great.
