### ISSUE TITLE
Driver interfering with mouse capture

### ISSUE THREAD

**Issue by JPVenson** [oblitum/Interception#71]
Hey,

I Installed the Interception diver properly and started to work on my Projekt. After some time i wanted to play some games again and observed that all my games keeps losing its Mouse capture. (For example Divinity 2).

It seems the Interception DLL is interfering with captured mice. 
After i uninstalled the driver it works fine again.

**Comment by oblitum** [comment]
Some games are known to take specific measures to block Interception, whose possible circumvention would be to alter driver sources and rebuild. Also without addition information there's nothing I can do at all.

**Comment by JPVenson** [comment]
What kind of information do you need?
