### ISSUE TITLE
Driver not recognized by UCR

### ISSUE THREAD

**Issue by zionhian** [oblitum/Interception#74]
Not sure if i am supposed to be posting this in the UCR github or this one. In ucr Core_interception no devices are found, which i suspect is the driver not being recognised. This issues only happens on my laptop for which i don't use an external keyboard.

**Comment by oblitum** [comment]
Hi. I have no idea what UCR means.

**Comment by zionhian** [comment]
Universal controller remaper by Snoothy. Using your driver you can map a keyboard into a 360 gamepad.
https://github.com/Snoothy/UCR

**Comment by oblitum** [comment]
I can't provide a solution on some third party. Maybe you can have a better luck asking there, or providing specific details regarding the library/driver usage alone.
