### ISSUE TITLE
Oblitum interception driver not loaded

### ISSUE THREAD

**Issue by Guduche** [oblitum/Interception#75]
If my mouse isn't connected (Bluetooth) when I start intercept (on start-up), I have this error: "Oblitum interception driver not loaded !".

If I try to start it later it works if the mouse is connected and doesn't if the mouse isn't connected.

If I have connected the mouse, it starts even if the mouse is disconnected later.

**Comment by oblitum** [comment]
The message "Oblitum interception driver not loaded !" is not part of this project, so I assume you're using some tool that makes use of this project, but for which I don't provide support.

**Comment by Guduche** [comment]
Ok thank's, sorry.
