### ISSUE TITLE
uninstalling process not seamless

### ISSUE THREAD

**Issue by tommy-mor** [oblitum/Interception#80]
I had to uninstall this driver because the most recent update to faceit AC blocks it,

the only way I was able to uninstall it was thanks to @filippobottega in #34 's instructions:

Windows 10. In Administrative CMD:

1. - install-interception.exe /install OK
2. - Reboot OK (Driver works well)
3. - install-interception.exe /uninstall FAIL with Error deleting \system32\drivers\keyboard.sys
4. - Reboot OK
5. - install-interception.exe /uninstall OK
6. - Reboot OK (Driver is uninstalled)

**Comment by oblitum** [comment]
It's quite possible that you used old binaries. The current ones have been updated to do pending file remotion, which will only occur on reboot.

**Comment by oblitum** [comment]
It was done to precisely fix this issue.

**Comment by tommy-mor** [comment]
👍
