### ISSUE TITLE
udevmon seems to make booting take longer

### ISSUE THREAD

**Issue by wizonesolutions** [oblitum/Interception#82]
![IMG_20190812_125754](https://user-images.githubusercontent.com/344116/62860814-b8874300-bd01-11e9-9f01-b163d63751f6.jpg)

I'm using the default suggested config file from caps2esc, and that's all I'm using. This job finished after about 1m12s.

```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        18.0.4
Codename:       Illyria
```

**Comment by oblitum** [comment]
You posted it on wrong repo.

Check this: https://gitlab.com/interception/linux/tools
