### ISSUE TITLE
Disable my laptops touchpad and Interception won't work anymore

### ISSUE THREAD

**Issue by machomuchacho** [oblitum/Interception#88]
Hello, I'm only using Interception to be able to remap mouse inputs into Playstation 4 controller inputs to play games on the PS Now but at first I thought it wasn't working, then I realised it was only working with my laptops touchpad and not my actual mouse (also it doesn't hide the cursor but maybe i'll find a fix for this by myself), so I went into my UEFI settings and disabled the touchpad but Interceptor won't work at all (with touchpad disabled). Tried installing it once again but an error message shows up : "Could not write to \system32\drivers"

What can I do ? Is there a way to swap IDs of both peripherals or something ? This sounds like easy but since I'm not a developper at all I don't know how to fix my problem.

Thanks.

**Comment by oblitum** [comment]
This project is a library only project _for developers_. It's not associated with a project called Intercep**tor**. That's an independent project that uses the Interception library and drivers, and if I recall correctly,  Intercep**tor** doesn't make use of mouse from Interception, just keyboard. I don't provide support for other people's code.

For install/uninstall with official command line installers you must use administrator prompt.

**Comment by machomuchacho** [comment]
It's just a typo, I wrote Interception in the name of the question. Of course the prompt was running as administrator. I use Interception with UCR (Iniversal Command Remapper). I thought the problem was UCR but actually no, that is why I'm writing here. Are you not going to help me just because I'm not a developer ? Who can I ask to then ?

**Comment by oblitum** [comment]
I don't provide support for non developers. This is a library project.
