### ISSUE TITLE
How to minimize "intercept.exe" to tray automatically when Windows start?

### ISSUE THREAD

**Issue by MikuGenius** [oblitum/Interception#89]
Thank you for help.I want to keep my taskbar clean,lol.

![66691054-7c06a200-ecc6-11e9-926d-f9f6beba9e46](https://user-images.githubusercontent.com/25473330/66693528-5c7a7400-ecdc-11e9-8d43-6aba79a128c7.png)

**Comment by oblitum** [comment]
This program is based on my library but it's not my program.
