### ISSUE TITLE
Interception causes keyboard to become unresponsive if it is unplugged

### ISSUE THREAD

**Issue by calico-crusade** [oblitum/Interception#93]
While interception is installed on my computer; if I unplug and then re-plugin a keyboard, the keyboard becomes unresponsive. The lights still work, ICUE (Corsairs lighting service) still detects the keyboard, but no key-strokes work at all. I have to fully restart the system to get the keyboard to come back. 

I am using Interception in a macro application I've developed that allows for a second keyboard to become a holistic macro keyboard. I am 100% confident that it is not my code that is causing the problem as the issue is present regardless of whether or not my application is running or has been run since the last time I restarted the computer.

Is there any fix for this or is anyone else running into the same issue?

Windows 10 Pro (v1903)
Corsair K70 RGB, Logitech 2 in 1 wireless track pad + keyboard.
Latest release of Interception.

**Comment by oblitum** [comment]
If reconnecting many times, it's not supported in free version. See #25.

**Comment by calico-crusade** [comment]
This should definitely be mentioned in the readme. $2200 is a steep price and way out of my price range and it would have been nice to know about this issue prior to starting development.

**Comment by MartinLichtblau** [comment]
Hey @oblitum, why don't you simply create an unsigned driver? 
Since you say you can't fix this bug, because then you have to sign it, which costs money.  There must be a solution. I've never seen a software project that is so adamant about not fixing a bug. If it's about the income this bug generates, I am sure there are other ways.

**Comment by MaverickMartyn** [comment]
Unfortunately this means I'm back to square one on my project.
I thought this would be a good fit, but this limitation has cost me hours of frustrating debugging, on/off over multiple months trying to track down this as the cause.
Please, for the love of all things, add this to the README.md.
Other than this, it's worked really well, but this was utterly frustrating.
If paying 2200$ is the only solution, I guess I'm out of luck. My project is a free open source application, so dropping that kind of mula is out of the question. :/
