### ISSUE TITLE
Slot is Invalidated Controller_Plug_In_Failed

### ISSUE THREAD

**Issue by hosnavch** [oblitum/Interception#95]
I've seen your other solutions for this error and tried them all. 
I was using ScpToolkit to connect my Dualshock 3 to my PC before so as you wrote on other issues, I thought that might be causing this problem.
-So I uninstalled ScpToolkit and restarted my pc. 
-I've downloaded and installed every necessary drivers.
-I uninstalled Interception using CMD following your steps on youtube.
-I reinstalled the necessary parts and rebooted.
And still having this problem.
Here is my log txt:
[splitter_log.txt](https://github.com/oblitum/Interception/files/4002971/splitter_log.txt)

**Comment by oblitum** [comment]
Simply have no idea of what you're talking about, I don't have any installation steps on YouTube and never heard of ScpToolkit before.
