### ISSUE TITLE
Windows 10 Support - error on install, "could not write do system32/drivers"

### ISSUE THREAD

**Issue by paradoxalan** [oblitum/Interception#96]
Hello, this issue was already posted here:
https://github.com/oblitum/Interception/issues/15

And following the uninstall/install method i can get it to work fine, BUT JUST FOR A FEW HOURS.
I repeat the process and works again for a while, and this goes on and on, and i have to keep doing this.
I can not get a clue why this happens, do you have any ideia??
Thanks.

**Comment by oblitum** [comment]
Not a clue. First time I'm learning of "temporary install".

**Comment by paradoxalan** [comment]
It seems something related to permissions/security on the drivers directory.
I'm trying to mess around with ownership of that dir.

**Comment by daubweb** [comment]
@paradoxalan 
did you have any success with this messing around? I tried the same thing but I didnt figure out a solution. Did you by any chance? How? :)

**Comment by oblitum** [comment]
I'd be interested in more information on this too. I'll close it for now as there's no information and issue has staled.
